version: "3.8"

services:
  django:
    entrypoint: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
#    command: tail -f
    ports:
      - 8000:8000
    restart: unless-stopped
#    volumes:
#      - .:/app

  postgres:
    image: postgres:13.3
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
