version: "3.8"

services:
  django:
    build:
      context: .
      args:
        - MEDIA_ROOT
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always
    volumes:
      - media:$MEDIA_ROOT

volumes:
  media:
