version: "3.8"

services:
  django:
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - .:/app

  postgres:
    env_file:
      - .env.dev
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  postgres:
  media:
