version: "3.8"

services:
  django:
    build:
      context: .
#      args:
#        - MEDIA_ROOT
    depends_on:
      - postgres
    env_file:
      - .env
#    environment:
#      - MEDIA_ROOT
    restart: always
    volumes:
      - media:/app/media/

volumes:
  media:
